# Generated by Django 5.0.7 on 2024-07-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_description_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('bags', 'Bags'), ('clothes', 'Clothes'), ('accessories', 'Accessories'), ('all', 'All')], default='all', max_length=100),
        ),
    ]
